<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $eco  = Category::where('name', 'Económico')->value('id');
        $int  = Category::where('name', 'Intermedio')->value('id');
        $suv  = Category::where('name', 'SUV')->value('id');
        $prem = Category::where('name', 'Premium')->value('id');
        $pick = Category::where('name', 'Pickup')->value('id');
        $van  = Category::where('name', 'Van / Minivan')->value('id');

        $vehicles = [
            // ── Económico ──────────────────────────────────────────────────
            ['category_id' => $eco,  'brand' => 'Toyota',     'model' => 'Yaris',         'year' => 2022, 'plate' => 'A001EC', 'price_per_day' => 35,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 2, 'current_mileage' => 12000, 'current_fuel_level' => 100, 'key_features' => 'Aire acondicionado, Bluetooth, Cámara de reversa'],
            ['category_id' => $eco,  'brand' => 'Kia',        'model' => 'Rio',            'year' => 2021, 'plate' => 'A002EC', 'price_per_day' => 32,  'transmission_type' => 'manual',     'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 2, 'current_mileage' => 20500, 'current_fuel_level' => 85,  'key_features' => 'Aire acondicionado, USB, Bluetooth'],
            ['category_id' => $eco,  'brand' => 'Chevrolet',  'model' => 'Spark',          'year' => 2020, 'plate' => 'A003EC', 'price_per_day' => 28,  'transmission_type' => 'manual',     'fuel_type' => 'gasolina',  'passenger_capacity' => 4, 'luggage_capacity' => 1, 'current_mileage' => 35000, 'current_fuel_level' => 70,  'key_features' => 'Aire acondicionado, Bluetooth'],
            ['category_id' => $eco,  'brand' => 'Nissan',     'model' => 'March',          'year' => 2021, 'plate' => 'A004EC', 'price_per_day' => 30,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 2, 'current_mileage' => 18000, 'current_fuel_level' => 90,  'key_features' => 'Aire acondicionado, Bluetooth, USB'],
            ['category_id' => $eco,  'brand' => 'Renault',    'model' => 'Logan',          'year' => 2020, 'plate' => 'A005EC', 'price_per_day' => 29,  'transmission_type' => 'manual',     'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 22000, 'current_fuel_level' => 80,  'key_features' => 'Aire acondicionado, Bluetooth'],
            ['category_id' => $eco,  'brand' => 'Suzuki',     'model' => 'Swift',          'year' => 2022, 'plate' => 'A006EC', 'price_per_day' => 31,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 2, 'current_mileage' => 9000,  'current_fuel_level' => 100, 'key_features' => 'Aire acondicionado, Apple CarPlay'],
            ['category_id' => $eco,  'brand' => 'Hyundai',    'model' => 'Grand i10',      'year' => 2023, 'plate' => 'A007EC', 'price_per_day' => 27,  'transmission_type' => 'manual',     'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 2, 'current_mileage' => 5000,  'current_fuel_level' => 100, 'key_features' => 'Aire acondicionado, Bluetooth, USB'],
            ['category_id' => $eco,  'brand' => 'Kia',        'model' => 'Picanto',        'year' => 2022, 'plate' => 'A008EC', 'price_per_day' => 26,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 4, 'luggage_capacity' => 1, 'current_mileage' => 8000,  'current_fuel_level' => 95,  'key_features' => 'Aire acondicionado, Bluetooth'],
            ['category_id' => $eco,  'brand' => 'Volkswagen', 'model' => 'Polo',           'year' => 2021, 'plate' => 'A009EC', 'price_per_day' => 33,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 2, 'current_mileage' => 14000, 'current_fuel_level' => 88,  'key_features' => 'Aire acondicionado, Android Auto, Cámara de reversa'],
            ['category_id' => $eco,  'brand' => 'Renault',    'model' => 'Sandero',        'year' => 2020, 'plate' => 'A010EC', 'price_per_day' => 28,  'transmission_type' => 'manual',     'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 2, 'current_mileage' => 25000, 'current_fuel_level' => 75,  'key_features' => 'Aire acondicionado, Bluetooth', 'status' => 'mantenimiento'],

            // ── Intermedio ─────────────────────────────────────────────────
            ['category_id' => $int,  'brand' => 'Toyota',     'model' => 'Corolla',        'year' => 2023, 'plate' => 'B001IN', 'price_per_day' => 50,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 8000,  'current_fuel_level' => 100, 'key_features' => 'Aire acondicionado, Apple CarPlay, Cámara de reversa, Control crucero'],
            ['category_id' => $int,  'brand' => 'Honda',      'model' => 'Civic',          'year' => 2022, 'plate' => 'B002IN', 'price_per_day' => 55,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 15300, 'current_fuel_level' => 90,  'key_features' => 'Aire acondicionado, Android Auto, Sensores de estacionamiento'],
            ['category_id' => $int,  'brand' => 'Mazda',      'model' => '3',              'year' => 2023, 'plate' => 'B003IN', 'price_per_day' => 52,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 11000, 'current_fuel_level' => 95,  'key_features' => 'Aire acondicionado, Apple CarPlay, Head-up Display'],
            ['category_id' => $int,  'brand' => 'Volkswagen', 'model' => 'Jetta',          'year' => 2022, 'plate' => 'B004IN', 'price_per_day' => 48,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 14000, 'current_fuel_level' => 85,  'key_features' => 'Aire acondicionado, Bluetooth, Pantalla táctil'],
            ['category_id' => $int,  'brand' => 'Nissan',     'model' => 'Sentra',         'year' => 2021, 'plate' => 'B005IN', 'price_per_day' => 45,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 19000, 'current_fuel_level' => 75,  'key_features' => 'Aire acondicionado, Android Auto'],
            ['category_id' => $int,  'brand' => 'Hyundai',    'model' => 'Elantra',        'year' => 2022, 'plate' => 'B006IN', 'price_per_day' => 47,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 13000, 'current_fuel_level' => 88,  'key_features' => 'Aire acondicionado, Apple CarPlay, Cámara de reversa'],
            ['category_id' => $int,  'brand' => 'Chevrolet',  'model' => 'Cruze',          'year' => 2021, 'plate' => 'B007IN', 'price_per_day' => 46,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 17000, 'current_fuel_level' => 80,  'key_features' => 'Aire acondicionado, WiFi, Cámara de reversa, Android Auto'],
            ['category_id' => $int,  'brand' => 'Subaru',     'model' => 'Impreza',        'year' => 2022, 'plate' => 'B008IN', 'price_per_day' => 53,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 10000, 'current_fuel_level' => 92,  'key_features' => 'AWD, Apple CarPlay, EyeSight, Control crucero'],
            ['category_id' => $int,  'brand' => 'Kia',        'model' => 'Cerato',         'year' => 2023, 'plate' => 'B009IN', 'price_per_day' => 44,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 6000,  'current_fuel_level' => 100, 'key_features' => 'Aire acondicionado, Apple CarPlay, Cámara 360°'],
            ['category_id' => $int,  'brand' => 'Peugeot',    'model' => '308',            'year' => 2022, 'plate' => 'B010IN', 'price_per_day' => 49,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 12000, 'current_fuel_level' => 85,  'key_features' => 'Aire acondicionado, Pantalla i-Cockpit, Android Auto', 'status' => 'mantenimiento'],

            // ── SUV ────────────────────────────────────────────────────────
            ['category_id' => $suv,  'brand' => 'Toyota',     'model' => 'RAV4',           'year' => 2023, 'plate' => 'C001SV', 'price_per_day' => 85,  'transmission_type' => 'automatica', 'fuel_type' => 'hibrido',   'passenger_capacity' => 5, 'luggage_capacity' => 4, 'current_mileage' => 5000,  'current_fuel_level' => 100, 'key_features' => 'Aire acondicionado, 4x4, Apple CarPlay, Cámara 360°, Control crucero adaptativo'],
            ['category_id' => $suv,  'brand' => 'Hyundai',    'model' => 'Tucson',         'year' => 2022, 'plate' => 'C002SV', 'price_per_day' => 75,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 4, 'current_mileage' => 18000, 'current_fuel_level' => 75,  'key_features' => 'Aire acondicionado, Bluetooth, Cámara de reversa, Sensores de estacionamiento'],
            ['category_id' => $suv,  'brand' => 'Jeep',       'model' => 'Wrangler',       'year' => 2023, 'plate' => 'C003SV', 'price_per_day' => 120, 'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 7500,  'current_fuel_level' => 100, 'key_features' => '4x4, Techo removible, Apple CarPlay, Control tracción'],
            ['category_id' => $suv,  'brand' => 'Ford',       'model' => 'Escape',         'year' => 2022, 'plate' => 'C004SV', 'price_per_day' => 80,  'transmission_type' => 'automatica', 'fuel_type' => 'hibrido',   'passenger_capacity' => 5, 'luggage_capacity' => 4, 'current_mileage' => 10000, 'current_fuel_level' => 95,  'key_features' => 'Aire acondicionado, SYNC 4, Cámara 360°'],
            ['category_id' => $suv,  'brand' => 'Nissan',     'model' => 'X-Trail',        'year' => 2022, 'plate' => 'C005SV', 'price_per_day' => 78,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 7, 'luggage_capacity' => 4, 'current_mileage' => 16000, 'current_fuel_level' => 80,  'key_features' => 'Aire acondicionado, Android Auto, 7 pasajeros, Cámara de reversa'],
            ['category_id' => $suv,  'brand' => 'Mitsubishi', 'model' => 'Outlander',      'year' => 2023, 'plate' => 'C006SV', 'price_per_day' => 82,  'transmission_type' => 'automatica', 'fuel_type' => 'hibrido',   'passenger_capacity' => 7, 'luggage_capacity' => 4, 'current_mileage' => 6000,  'current_fuel_level' => 100, 'key_features' => 'Plug-in Hybrid, 7 pasajeros, Apple CarPlay, AWD'],
            ['category_id' => $suv,  'brand' => 'Kia',        'model' => 'Sportage',       'year' => 2023, 'plate' => 'C007SV', 'price_per_day' => 77,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 4, 'current_mileage' => 9000,  'current_fuel_level' => 95,  'key_features' => 'Aire acondicionado, Apple CarPlay, Cámara 360°, Sensores de estacionamiento'],
            ['category_id' => $suv,  'brand' => 'Chevrolet',  'model' => 'Equinox',        'year' => 2022, 'plate' => 'C008SV', 'price_per_day' => 73,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 4, 'current_mileage' => 20000, 'current_fuel_level' => 78,  'key_features' => 'Aire acondicionado, WiFi, Android Auto, Control crucero adaptativo'],
            ['category_id' => $suv,  'brand' => 'Honda',      'model' => 'CR-V',           'year' => 2023, 'plate' => 'C009SV', 'price_per_day' => 83,  'transmission_type' => 'automatica', 'fuel_type' => 'hibrido',   'passenger_capacity' => 5, 'luggage_capacity' => 4, 'current_mileage' => 4000,  'current_fuel_level' => 100, 'key_features' => 'Híbrido, Honda Sensing, Apple CarPlay, Cámara 360°'],
            ['category_id' => $suv,  'brand' => 'Mazda',      'model' => 'CX-5',           'year' => 2022, 'plate' => 'C010SV', 'price_per_day' => 79,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 4, 'current_mileage' => 11000, 'current_fuel_level' => 88,  'key_features' => 'Aire acondicionado, i-Activ AWD, Apple CarPlay, Head-up Display'],

            // ── Premium ────────────────────────────────────────────────────
            ['category_id' => $prem, 'brand' => 'BMW',         'model' => 'Serie 3',       'year' => 2023, 'plate' => 'D001PM', 'price_per_day' => 150, 'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 3000,  'current_fuel_level' => 100, 'key_features' => 'Cuero, Pantalla táctil, Apple CarPlay, Techo panorámico, Control crucero adaptativo'],
            ['category_id' => $prem, 'brand' => 'Tesla',       'model' => 'Model 3',       'year' => 2023, 'plate' => 'D002PM', 'price_per_day' => 180, 'transmission_type' => 'automatica', 'fuel_type' => 'electrico', 'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 7200,  'current_fuel_level' => 60,  'key_features' => 'Pantalla táctil 15", Piloto automático, Carga rápida, Actualizaciones OTA', 'status' => 'mantenimiento'],
            ['category_id' => $prem, 'brand' => 'Mercedes-Benz', 'model' => 'Clase C',     'year' => 2023, 'plate' => 'D003PM', 'price_per_day' => 200, 'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 2000,  'current_fuel_level' => 100, 'key_features' => 'MBUX, Cuero Nappa, Techo panorámico, Asistente de conducción'],
            ['category_id' => $prem, 'brand' => 'Audi',        'model' => 'A4',            'year' => 2022, 'plate' => 'D004PM', 'price_per_day' => 170, 'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 4000,  'current_fuel_level' => 100, 'key_features' => 'MMI Touch, Cuero, Virtual Cockpit, Quattro AWD'],
            ['category_id' => $prem, 'brand' => 'Lexus',       'model' => 'IS',            'year' => 2022, 'plate' => 'D005PM', 'price_per_day' => 160, 'transmission_type' => 'automatica', 'fuel_type' => 'hibrido',   'passenger_capacity' => 5, 'luggage_capacity' => 3, 'current_mileage' => 5500,  'current_fuel_level' => 100, 'key_features' => 'Cuero, Mark Levinson Audio, Híbrido, Control crucero radar'],
            ['category_id' => $prem, 'brand' => 'BMW',         'model' => 'X5',            'year' => 2023, 'plate' => 'D006PM', 'price_per_day' => 250, 'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 5, 'current_mileage' => 1500,  'current_fuel_level' => 100, 'key_features' => 'xDrive AWD, Cuero, Techo panorámico, Apple CarPlay, Cámara 360°'],
            ['category_id' => $prem, 'brand' => 'Porsche',     'model' => 'Cayenne',       'year' => 2022, 'plate' => 'D007PM', 'price_per_day' => 300, 'transmission_type' => 'automatica', 'fuel_type' => 'hibrido',   'passenger_capacity' => 5, 'luggage_capacity' => 4, 'current_mileage' => 3000,  'current_fuel_level' => 100, 'key_features' => 'Plug-in Hybrid, Cuero, Bose Audio, PCM, Techo panorámico'],
            ['category_id' => $prem, 'brand' => 'Mercedes-Benz', 'model' => 'GLE',         'year' => 2023, 'plate' => 'D008PM', 'price_per_day' => 280, 'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 5, 'current_mileage' => 2500,  'current_fuel_level' => 100, 'key_features' => 'MBUX, 4MATIC AWD, Cuero Nappa, Techo panorámico, Asientos masajeadores'],

            // ── Pickup ─────────────────────────────────────────────────────
            ['category_id' => $pick, 'brand' => 'Toyota',     'model' => 'Hilux',          'year' => 2022, 'plate' => 'E001PK', 'price_per_day' => 90,  'transmission_type' => 'manual',     'fuel_type' => 'diesel',    'passenger_capacity' => 5, 'luggage_capacity' => 6, 'current_mileage' => 30000, 'current_fuel_level' => 100, 'key_features' => 'Aire acondicionado, 4x4, Bluetooth, Doble cabina'],
            ['category_id' => $pick, 'brand' => 'Ford',       'model' => 'Ranger',          'year' => 2023, 'plate' => 'E002PK', 'price_per_day' => 95,  'transmission_type' => 'automatica', 'fuel_type' => 'diesel',    'passenger_capacity' => 5, 'luggage_capacity' => 6, 'current_mileage' => 22000, 'current_fuel_level' => 95,  'key_features' => 'Aire acondicionado, SYNC 3, 4x4, Control de descenso'],
            ['category_id' => $pick, 'brand' => 'Mitsubishi', 'model' => 'L200',            'year' => 2021, 'plate' => 'E003PK', 'price_per_day' => 85,  'transmission_type' => 'manual',     'fuel_type' => 'diesel',    'passenger_capacity' => 5, 'luggage_capacity' => 6, 'current_mileage' => 28000, 'current_fuel_level' => 90,  'key_features' => 'Aire acondicionado, 4x4, Bluetooth, Super Select 4WD'],
            ['category_id' => $pick, 'brand' => 'Nissan',     'model' => 'Frontier',        'year' => 2022, 'plate' => 'E004PK', 'price_per_day' => 88,  'transmission_type' => 'automatica', 'fuel_type' => 'diesel',    'passenger_capacity' => 5, 'luggage_capacity' => 6, 'current_mileage' => 15000, 'current_fuel_level' => 85,  'key_features' => 'Aire acondicionado, Android Auto, 4x4, Cámara de reversa'],
            ['category_id' => $pick, 'brand' => 'Chevrolet',  'model' => 'Colorado',        'year' => 2022, 'plate' => 'E005PK', 'price_per_day' => 92,  'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 5, 'luggage_capacity' => 6, 'current_mileage' => 18000, 'current_fuel_level' => 80,  'key_features' => 'Aire acondicionado, Apple CarPlay, 4x4, Control tracción'],
            ['category_id' => $pick, 'brand' => 'Isuzu',      'model' => 'D-Max',           'year' => 2021, 'plate' => 'E006PK', 'price_per_day' => 83,  'transmission_type' => 'manual',     'fuel_type' => 'diesel',    'passenger_capacity' => 5, 'luggage_capacity' => 6, 'current_mileage' => 32000, 'current_fuel_level' => 88,  'key_features' => 'Aire acondicionado, 4x4, Bluetooth, Doble cabina', 'status' => 'mantenimiento'],

            // ── Van / Minivan ──────────────────────────────────────────────
            ['category_id' => $van,  'brand' => 'Kia',        'model' => 'Carnival',        'year' => 2022, 'plate' => 'F001VN', 'price_per_day' => 110, 'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 8, 'luggage_capacity' => 5, 'current_mileage' => 9500,  'current_fuel_level' => 95,  'key_features' => 'Aire acondicionado, Apple CarPlay, Asientos reclinables, Cámara 360°'],
            ['category_id' => $van,  'brand' => 'Toyota',     'model' => 'Sienna',          'year' => 2023, 'plate' => 'F002VN', 'price_per_day' => 120, 'transmission_type' => 'automatica', 'fuel_type' => 'hibrido',   'passenger_capacity' => 8, 'luggage_capacity' => 5, 'current_mileage' => 6000,  'current_fuel_level' => 100, 'key_features' => 'Híbrido AWD, 8 pasajeros, Pantalla trasera, Puertas correderas eléctricas'],
            ['category_id' => $van,  'brand' => 'Volkswagen', 'model' => 'Caravelle',       'year' => 2022, 'plate' => 'F003VN', 'price_per_day' => 130, 'transmission_type' => 'automatica', 'fuel_type' => 'diesel',    'passenger_capacity' => 9, 'luggage_capacity' => 6, 'current_mileage' => 14000, 'current_fuel_level' => 85,  'key_features' => '9 pasajeros, Bluetooth, Climatizador doble, Cámara de reversa'],
            ['category_id' => $van,  'brand' => 'Honda',      'model' => 'Odyssey',         'year' => 2022, 'plate' => 'F004VN', 'price_per_day' => 115, 'transmission_type' => 'automatica', 'fuel_type' => 'gasolina',  'passenger_capacity' => 8, 'luggage_capacity' => 5, 'current_mileage' => 11000, 'current_fuel_level' => 90,  'key_features' => 'Aire acondicionado, Apple CarPlay, Puertas correderas automáticas, Cámara de reversa'],
            ['category_id' => $van,  'brand' => 'Chrysler',   'model' => 'Pacifica',        'year' => 2022, 'plate' => 'F005VN', 'price_per_day' => 118, 'transmission_type' => 'automatica', 'fuel_type' => 'hibrido',   'passenger_capacity' => 7, 'luggage_capacity' => 5, 'current_mileage' => 8000,  'current_fuel_level' => 92,  'key_features' => 'Plug-in Hybrid, Uconnect, Apple CarPlay, Puertas correderas eléctricas'],
        ];

        foreach ($vehicles as $data) {
            Vehicle::create(array_merge(['status' => 'disponible'], $data));
        }
    }
}
